[[themes]]
name = "yoru"
[themes.palette]
background = "#0c0e0f"
foreground = "#edeff0"
black = "#232526"
red = "#df5b61"
green = "#78b892"
yellow = "#de8f78"
blue = "#6791c9"
magenta = "#bc83e3"
cyan = "#67afc1"
white = "#e4e6e7"
bright_black = "#2c2e2f"
bright_red = "#e8646a"
bright_green = "#81c19b"
bright_yellow = "#e79881"
bright_blue = "#709ad2"
bright_magenta = "#c58cec"
bright_cyan = "#70b8ca"
bright_white = "#f2f4f5"
